export const ADD_ARTICLE = 'ADD_ARTICLE'
export const FOUND_BAD_WORD = 'FOUND_BAD_WORD'
export const DATA_LOADED = 'DATA_LOADED'
export const FETCH_FAILURE = 'FETCH_FAILURE'
export const LOAD_DATA = 'LOAD_DATA'
